server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000

spring:
  datasource:
    url: ENC(nHZhnxakjgfzWesx28LnS/aDcBVb5OekZRc0wl97CBGovy9JGnG+ofXsvydTs9Qf11Iqnt2oPcM=)
    username: ENC(ZApxsDkfif5LYLP3qlw8Mg==)
    password: ENC(6EVKjZXwrzBL+q/bQkGHQg==)
    driver-class-name: com.mysql.cj.jdbc.Driver

# JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

# Hibernate Configuration
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate:
      type:
        descriptor.sql: trace
